name: my-portfolio
services:
- name: api
  github:
    repo: your-username/my-portfolio
    branch: main
  dockerfile_path: Dockerfile
  envs:
  - key: DB_HOST
    value: ${DB_HOST}
  - key: DB_USER
    value: ${DB_USER}
  - key: DB_PASSWORD
    value: ${DB_PASSWORD}
  - key: DB_NAME
    value: ${DB_NAME} 